x-django-common: &django-common
  image: alphard:latest
  environment:
    NPM_BIN_PATH: "/usr/bin/npm"
    DEBUG: "False"
    SECRET_KEY_FILE: /run/secrets/alphard_secret_key
    ALLOWED_HOSTS_FILE: /run/secrets/alphard_allowed_hosts

    DB_PASSWORD_FILE: /run/secrets/alphard_db_password
    DB_HOST: "alphard_db"
    REDIS_CACHE_URL: "redis://alphard_redis:6379/0"
    REDIS_URL: "redis://alphard_redis:6379/1"
    CELERY_BROKER_URL: "redis://alphard_redis:6379/2"
    CELERY_RESULT_BACKEND: "redis://alphard_redis:6379/3"

    EMAIL_HOST_FILE: /run/secrets/alphard_email_host
    EMAIL_PORT_FILE: /run/secrets/alphard_email_port
    EMAIL_USE_TLS_FILE: /run/secrets/alphard_email_use_tls
    EMAIL_USE_SSL_FILE: /run/secrets/alphard_email_use_ssl
    EMAIL_HOST_USER_FILE: /run/secrets/alphard_email_host_user
    EMAIL_HOST_PASSWORD_FILE: /run/secrets/alphard_email_host_password
    DEFAULT_FROM_EMAIL_FILE: /run/secrets/alphard_default_from_email
    ADMINS_FILE: /run/secrets/alphard_admins
    SERVER_EMAIL_FILE: /run/secrets/alphard_server_email

    CSRF_COOKIE_SECURE_FILE: /run/secrets/alphard_csrf_cookie_secure
    SESSION_COOKIE_SECURE_FILE: /run/secrets/alphard_session_cookie_secure
  secrets:
    - alphard_secret_key
    - alphard_allowed_hosts
    - alphard_db_password
    - alphard_email_host
    - alphard_email_port
    - alphard_email_use_tls
    - alphard_email_use_ssl
    - alphard_email_host_user
    - alphard_email_host_password
    - alphard_default_from_email
    - alphard_admins
    - alphard_server_email
    - alphard_csrf_cookie_secure
    - alphard_session_cookie_secure
  deploy:
    replicas: 1
  networks:
    - internal

services:
  web:
    <<: *django-common
    command: gunicorn --bind 0.0.0.0:8000 --workers 3 alphard.wsgi:application
    volumes:
      - static_files:/usr/src/app/staticfiles
      - media_data:/usr/src/app/media

  celery:
    <<: *django-common
    command: celery --app=alphard worker --loglevel=info

  celery_beat:
    <<: *django-common
    command: celery --app=alphard beat --loglevel=info

  redis:
    image: redis:8-bookworm
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    deploy:
      replicas: 1
    networks:
      - internal

  db:
    image: postgres:17.6-bookworm
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: alphard
      POSTGRES_PASSWORD_FILE: /run/secrets/alphard_db_password
      POSTGRES_DB: alphard
    secrets:
      - alphard_db_password
    deploy:
      replicas: 1
    networks:
      - internal

  nginx:
    image: nginx:1.28.0-bookworm
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - static_files:/usr/src/app/staticfiles:ro
      - media_data:/usr/src/app/media
    deploy:
      replicas: 1
    networks:
      - internal

secrets:
  alphard_allowed_hosts:
    external: true
  alphard_secret_key:
    external: true
  alphard_db_password:
    external: true
  alphard_email_host:
    external: true
  alphard_email_port:
    external: true
  alphard_email_use_tls:
    external: true
  alphard_email_use_ssl:
    external: true
  alphard_email_host_user:
    external: true
  alphard_email_host_password:
    external: true
  alphard_default_from_email:
    external: true
  alphard_admins:
    external: true
  alphard_server_email:
    external: true
  alphard_csrf_cookie_secure:
    external: true
  alphard_session_cookie_secure:
    external: true

networks:
  internal:
    driver: overlay

volumes:
  postgres_data:
  static_files:
  media_data:
  redis_data:
