# Generated by Django 5.2.8 on 2025-11-20 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_customgroup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customgroup',
            options={'verbose_name': 'group', 'verbose_name_plural': 'groups'},
        ),
    ]
