"""
Django settings for alphard project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/

For deployment best practices and security checklist, see
https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/
"""

from pathlib import Path
import environ

env = environ.Env(
    DEBUG=(bool, True)
)

# Build paths inside the project like this: BASE_DIR / 'subdir'
BASE_DIR = Path(__file__).resolve().parent.parent

environ.Env.read_env(BASE_DIR / '.env')

# Required by django-tailwind package as npm detection always fails irrespective of platform,
# and irrespective of if the npm executable is on the PATH. Default is for Windows due to ensure
# ease of development.
NPM_BIN_PATH = env('NPM_BIN_PATH', default=r'C:\\Program Files\\nodejs\\npm.cmd')

# Security configuration
# https://docs.djangoproject.com/en/5.2/topics/security/

# SECURITY WARNING: Ensure DEBUG is set to false in production. Set to True by default.
DEBUG = env('DEBUG')

# SECURITY WARNING: Do not expose SECRET_KEY in production. If you do decide to
# rotate keys somehow as I still don't know how to do it with docker, put the old keys
# in the SECRET_KEY_FALLBACKS list and keep it there for at most 3 months.
SECRET_KEY = env('SECRET_KEY', default='django-insecure-fnmrrc9h!ne^zudbm_!o2--_((e=hmz+y02i-i84o4w76drx5e')
SECRET_KEY_FALLBACKS = env.list("SECRET_KEY_FALLBACKS", default=[])

# List of host/domain names that this Django site can serve.
# In development, Localhost, 127.0.0.1, and ::1 are allowed by default.
ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=[])

# Nginx should serve the website in production, or another reverse proxy if you're
# not relying on Docker. For testing purposes before full deployment, it's important to
# disable cookie security as cookies would not be sent back to the server otherwise.
if not DEBUG:
    CSRF_COOKIE_SECURE = env("CSRF_COOKIE_SECURE", default=True)
    SESSION_COOKIE_SECURE = env("SESSION_COOKIE_SECURE", default=True)
    USE_X_FORWARDED_HOST = True
    USE_X_FORWARDED_PORT = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'tailwind',
    'theme',
    'blog',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Provide the browser reload middleware in development. It's not needed in production
# and will just slow down the server.
if DEBUG:
    INSTALLED_APPS += ["django_browser_reload"]
    MIDDLEWARE += ["django_browser_reload.middleware.BrowserReloadMiddleware"]

ROOT_URLCONF = 'alphard.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

TAILWIND_APP_NAME = 'theme'

WSGI_APPLICATION = 'alphard.wsgi.application'

# Database
# Please note that the app only works with PostgreSQL due to ACID compliancy.
# I may also rely on Postgres specific features in the future.
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': env('DB_NAME', default='alphard'),
        'USER': env('DB_USER', default='alphard'),
        'PASSWORD': env('DB_PASSWORD', default='password'),
        'HOST': env('DB_HOST', default='localhost'),
        'PORT': env.int('DB_PORT', default=5432),
    }
}

# Cache configuration
# As I had planned to use Redis for rate limiting, I didn't find a reason not to use
# it for caching as well.
# https://docs.djangoproject.com/en/5.2/topics/cache/

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": env("REDIS_CACHE_URL", default="redis://localhost:6379/0"),
    }
}

# Session configuration
# https://docs.djangoproject.com/en/5.2/topics/http/sessions/

SESSION_ENGINE = 'django.contrib.sessions.backends.cached_db'

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    { 'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator' },
    { 'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator' },
    { 'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator' },
    { 'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator' },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# Django doesn't automatically serve static and media files in production.
# Use nginx or another web server instead if you're not using docker.
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files
# https://docs.djangoproject.com/en/5.2/topics/files/

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Email configuration
# Please note that ADMINS will receive an email whenever a 500 error is raised.
# https://docs.djangoproject.com/en/5.2/topics/email/

EMAIL_HOST = env('EMAIL_HOST', default='sandbox.smtp.mailtrap.io')
EMAIL_PORT = env.int('EMAIL_PORT', default=587)
EMAIL_USE_TLS = env.bool('EMAIL_USE_TLS', default=True) # Don't set both TLS and SSL to True.
EMAIL_USE_SSL = env.bool('EMAIL_USE_SSL', default=False)
EMAIL_HOST_USER = env('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = env('DEFAULT_FROM_EMAIL', default='webmaster@localhost')

ADMINS = env.list("ADMINS", default=[])
SERVER_EMAIL = env("SERVER_EMAIL", default="root@localhost")

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom user model
# https://docs.djangoproject.com/en/5.2/topics/auth/customizing/#auth-custom-user

AUTH_USER_MODEL = 'blog.User'

# Redis
# This url is used for rate limiting purposes, and it's recommended to make it distinct.

REDIS_URL = env("REDIS_URL", default="redis://localhost:6379/1")

# Celery

CELERY_BROKER_URL = env("CELERY_BROKER_URL", default="redis://localhost:6379/2")
CELERY_RESULT_BACKEND = env("CELERY_RESULT_BACKEND", default="redis://localhost:6379/3")
